apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-phpfpm
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-phpfpm
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-phpfpm
    spec:
      containers:
      - name: {{ template "fullname" . }}-phpfpm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.laravelService.phpfpmPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: "DB_CONNECTION"
          value: "pgsql"
        - name: "DB_HOST"
          value: "localhost"
        - name: "DB_PORT"
          value: "5432"
        - name: "DB_DATABASE"
          value: "postgres"
        - name: "DB_USERNAME"
          value: "admin"
        - name: "DB_PASSWORD"
          value: "password"
        - name: "APP_KEY"
          value: "base64:goa6gXPQXp620j2nz1kd95ix70OVutzXHHPJyQ09+24="
        - name: "APP_NAME"
          value: "Laravel"
        - name: "APP_ENV"
          value: "local"
        - name: "APP_DEBUG"
          value: "true"
        - name: "APP_URL"
          value: "http://localhost:8080"
        - name: "REDIS_HOST"
          value: "redis-master"
        - name: "REDIS_PORT"
          value: "6379"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.laravelService.phpfpmPort }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-nginx
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-nginx
    spec:
      containers:
      - name: {{ template "fullname" . }}-nginx
        image: "bitnami/nginx:latest"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.nginxService.internalPort }}
        - name: https
          containerPort: 8443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: nginx-config
          mountPath: /opt/bitnami/nginx/conf/server_blocks
      volumes:
      - name: nginx-config
        configMap:
          name: {{ template "fullname" . }}
